name: CI

on: 
    pull_request:  
        branches: [main]
    push: 
        branches: [main]
    merge_group: {}

permissions:
    contents: read

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
              with:
                    fetch-depth: 0
                    persist-credentials: false

            - uses: better-auth/shared-workflows/.github/actions/setup-pnpm@08e5520e7a829b03bee1152913682b67d2ba44b1

            - name: Build
              run: pnpm build

            - name: Test
              run: pnpm test

            - name: Typecheck
              run: pnpm typecheck
