name: Lint GitHub Actions

on:
  pull_request:
    paths:
      - ".github/actions/**"
      - ".github/workflows/**"
      - ".github/zizmor.yml"
  push:
    branches: [main]
    paths:
      - ".github/actions/**"
      - ".github/workflows/**"
      - ".github/zizmor.yml"

permissions: {}

jobs:
  lint:
    permissions:
      contents: read
    uses: better-auth/shared-workflows/.github/workflows/lint-github-actions.yml@08e5520e7a829b03bee1152913682b67d2ba44b1

  zizmor:
    if: github.event_name == 'pull_request'
    permissions:
      actions: read
      contents: read
    uses: better-auth/shared-workflows/.github/workflows/zizmor.yml@08e5520e7a829b03bee1152913682b67d2ba44b1

  zizmor-code-scanning:
    if: github.event_name == 'push'
    permissions:
      actions: read
      contents: read
      security-events: write
    uses: better-auth/shared-workflows/.github/workflows/zizmor-code-scanning.yml@08e5520e7a829b03bee1152913682b67d2ba44b1
